@startmindmap
* Video 5
** Analysis
***:Past
Explain How and Why somethings happened
;
*** Qualitative
**** Explain how and why things happened
*** Quantitative
**** data + how sales decrease last summer
** Analytics
***:Future
Explore potential future events
;
*** Qualitative
**** Forecast future trends
*** Quantitative
**** Forecast highest sales base on past data
** Method
***:Qualitative /định tính/
intuition /trực giác/ + analysis
;
***:Quantitative /định lượng/
formulas + algorithms
;

@endmindmap