@startmindmap
*:Video 7
BI, ML and AI
;
**[#SkyBlue] Business
*** Analysis (Past)
****[#SkyBlue] Business Case Study
****[#DodgerBlue] Preliminary Data Report
****[#OrangeRed] Business Intelligence
*****[#OrangeRed] Reporting with Visual
*****[#OrangeRed] Creating Dashboards
*****[#YellowGreen] Machine Learning
******[#Orange] Creating Real-time Dashboards
***** Note
******:analyse past data and extract useful insights
;
******:create appropriate models
;
*** Analytics (Future)
****[#SkyBlue] Qualitative Analytics
****[#DodgerBlue] Sales Forecasting
****[#YellowGreen] Machine Learning
*****[#PaleGreen] Client Retention
*****[#PaleGreen] Fraud Prevention
**[#LightPink] Data
***[#SeaGreen] Data Science
**** Analysis (Past)
*****[#DodgerBlue] Preliminary Data Report
*****[#OrangeRed] Business Intelligence
******[#OrangeRed] Reporting with Visual
******[#OrangeRed] Creating Dashboards
*****[#YellowGreen] Machine Learning
******[#Orange] Creating Real-time Dashboards
**** Analytics (Future)
*****[#DodgerBlue] Sales Forecasting
*****[#SeaGreen] Optimization of Drilling Operations
*****[#YellowGreen] Machine Learning
******[#PaleGreen] Client Retention
******[#PaleGreen] Fraud Prevention
*** Analytics (Future)
****[#LightPink] Digital Signal Processing
**[#DeepPink] Atificial Intelligence
*** Analysis (Past)
****[#YellowGreen] Machine Learning
*****[#Orange] Creating Real-time Dashboards
*** Analytics (Future)
****[#YellowGreen] Machine Learning
*****[#PaleGreen] Client Retention
*****[#PaleGreen] Fraud Prevention
****[#DeepPink] Symbolic Reasoning
**** Note
*****:simulating human knowledge and decision makeing with computers
;
** Note
***:__Data science__ is a part of Data Analytics which is mostly the part
that uses complex mathematical, statistical and programming tools
;
***:__Data science__ is a discipline reliant on data availability,
while business analytics does not completely rely on data
;
***:__Data science__ can be used to improve the accuracy of predictions based on 
data extracted from various activities typical for drilling efficiency
;
***[#LightPink] Digital Signal Processing

@endmindmap