@startmindmap
*:The six step
of the data analysis;
**:**Ask**
First up, the analysts needed to define
what the project would look like
and what would qualify as a successful result.
So, to determine these things,
they **asked** effective questions and collaborated
with leaders and managers
who were interested in the outcome
of their people analysis;
**:**Prepare**
It all started with solid **preparation**.
The group built a timeline of three months
and decided how they wanted to relay their progress
to interested parties. Also during this step,
the analysts identified what data they needed
to achieve the successful result they identified
in the previous step;
@endmindmap