@startmindmap
* Analytical thinking
**:**Root cause**
The reason why a problem occurs;
***:**Five why**
Ask **why?** five times to reveal the root cause;
**:**Gap analysis**
A method for examining and evaluating
how a process works currently in order to
get where you want to be in the future;
***:**Example**
The general approach to gap analysis is
understanding where you are now compared to
where you want to be. Then you can identify the gaps
that exist between the current
and future state
\and determine how to bridge them;
@endmindmap 