@startmindmap
* Data analyst skills
**:**Analytical skills**
The qualities and characteristics associated with solving problems using facts;
**:**A technical mindset**
The analytical skill that involves breaking processes down
into smaller steps and working with them in an orderly, logical way;
**:**Data design**
The analytical skill that involves how you organize information;
**:**Understanding context**
The analytical skill that has to do with how you group things into categories;
**:**Data strategy**
The analytical skill that involves managing the processes
and tools used in data analysis;
@endmindmap 