@startmindmap
* Data
**:**Curiosity**
Wanting to learn something;
** **Understanding context**
***:**Context**
The condition in which something exists or happens;
**:**Having a technical mindset**
The ability to break things down into smaller steps
or pieces and work with them in an orderly
and logical way;
**:**Data design**
How you organize information;
**:**Data strategy**
The management of the people, processes and 
tools used in data analysis;
@endmindmap 