@startmindmap
* Stages of data life cycle
**:**Plan**
Decide what kind of data is needed, how it will be managed,
and who will be responsible for it.;
**:**Capture**
Collect or bring in data from a variety of different sources.;
**:**Manage**
Care for and maintain the data. This includes determining
how and where it is stored and the tools used to do so.;
**:**Analyze**
Use the data to solve problems, make decisions, and support business goals.;
**:**Archive**
Keep relevant data stored for long-term and future reference.;
**:**Destroy**
Remove data from storage and delete any shared copies of the data.;
@endmindmap 